### ISSUE TITLE
'CONFIG' call breaks this for hosted Redis instances

### ISSUE THREAD

**Issue by tylerjharden** [dboissier/nosql4idea#7]
When connecting to a Redis instance that is hosted, in this case AWS ElastiCache, the CONFIG command for Redis is disabled with no option to enable it (which is desired default secure behavior and recommended by Redis anyways).

Unfortunately I have not found a workaround to get this plugin to not call CONFIG when attempting to connect, and thus cannot use the plugin for this server.

Not sure why you're calling it to begin with, but hopefully you can shine some light on this.

**Comment by tylerjharden** [comment]
More specifically when the plugin is grabbing the list of databases on Redis through Jedis, which drops into a CONFIG GET and fails:

```
ERR unknown command 'CONFIG'
redis.clients.jedis.exceptions.JedisDataException: ERR unknown command 'CONFIG'
    at redis.clients.jedis.Protocol.processError(Protocol.java:117)
    at redis.clients.jedis.Protocol.process(Protocol.java:151)
    at redis.clients.jedis.Protocol.read(Protocol.java:205)
    at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:297)
    at redis.clients.jedis.Connection.getBinaryMultiBulkReply(Connection.java:233)
    at redis.clients.jedis.Connection.getMultiBulkReply(Connection.java:226)
    at redis.clients.jedis.Jedis.configGet(Jedis.java:2541)
    at org.codinjutsu.tools.nosql.redis.logic.RedisClient.loadServer(RedisClient.java:62)
    at org.codinjutsu.tools.nosql.DatabaseVendorClientManager.loadServer(DatabaseVendorClientManager.java:65)
    at org.codinjutsu.tools.nosql.NoSqlExplorerPanel$2.run(NoSqlExplorerPanel.java:145)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:366)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
```

**Comment by dboissier** [comment]
Hi,

thanks for this info. I will have a look on an another way to get database info

**Comment by dboissier** [comment]
Hi,

About your Redis instance, do you have a single database access?
